// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Workout_Shop.Data;

#nullable disable

namespace Workout_Shop.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240524172248_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Workout_Shop.Models.Entites.Gyms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gyms");
                });

            modelBuilder.Entity("Workout_Shop.Models.Entites.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("Workout_Shop.Models.Entites.MainInstructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MainInstructors");
                });

            modelBuilder.Entity("Workout_Shop.Models.Entites.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GymId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MainInstructorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutCategory")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("MainInstructorId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("Workout_Shop.Models.Relationships.Instructor_Plan", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InstructorId", "PlanId");

                    b.HasIndex("PlanId");

                    b.ToTable("Instructor_Plans");
                });

            modelBuilder.Entity("Workout_Shop.Models.Entites.Plan", b =>
                {
                    b.HasOne("Workout_Shop.Models.Entites.Gyms", "Gyms")
                        .WithMany("Workouts")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workout_Shop.Models.Entites.MainInstructor", "MainInstructor")
                        .WithMany("Workouts")
                        .HasForeignKey("MainInstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gyms");

                    b.Navigation("MainInstructor");
                });

            modelBuilder.Entity("Workout_Shop.Models.Relationships.Instructor_Plan", b =>
                {
                    b.HasOne("Workout_Shop.Models.Entites.Instructor", "Instructor")
                        .WithMany("Instructor_Workout")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workout_Shop.Models.Entites.Plan", "Plan")
                        .WithMany("Instructor_Plan")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Workout_Shop.Models.Entites.Gyms", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("Workout_Shop.Models.Entites.Instructor", b =>
                {
                    b.Navigation("Instructor_Workout");
                });

            modelBuilder.Entity("Workout_Shop.Models.Entites.MainInstructor", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("Workout_Shop.Models.Entites.Plan", b =>
                {
                    b.Navigation("Instructor_Plan");
                });
#pragma warning restore 612, 618
        }
    }
}
